name: build_latest_release_multi_images
on:
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  build_multi_latest_release_tag:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          tag_name: ${{ github.ref }}
      - name: "login docker hub"
        run: |
          podman login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}} docker.io
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}}
      - run: |
          sudo apt-get update
          sudo apt-get -y install qemu-user-static buildah less git make podman clamav clamav-freshclam
        name: 'install dev deps'
      - name: Sets env vars
        run: |
          release_tag_redirect=$(curl -s https://github.com/curl/curl/releases/latest -w'%{redirect_url}\n' -o /dev/null)
          latest_release_ref=$(basename ${release_tag_redirect})
          echo "TAG_REF=$latest_release_ref" >> $GITHUB_ENV
          rel=${latest_release_ref:5}
          release_image_tag="${rel//_/.}"
          echo "REL=$release_image_tag" >> $GITHUB_ENV
      - run: buildah unshare make branch_or_ref=$TAG_REF release_tag=$REL multibuild
        name: 'build multi image'
      - run: buildah unshare make dist_name=localhost/curl-multi release_tag=$REL test
        name: 'test image'
      - run: make image_name=localhost/curl-multi:${REL} scan
        name: 'security scan image'
      - name: 'push release to docker hub'
        run: |
          buildah manifest push --format v2s2 --all localhost/curl-multi:$REL "docker://docker.io/flomesh/curl:${REL}"
          buildah manifest push --format v2s2 --all localhost/curl-multi:$REL "docker://docker.io/flomesh/curl:latest"
          buildah manifest push --format v2s2 --all localhost/curl-base-multi:$REL "docker://docker.io/flomesh/curl-base:${REL}"
          buildah manifest push --format v2s2 --all localhost/curl-base-multi:$REL "docker://docker.io/flomesh/curl-base:latest"