name: build_master_images
on:
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build_master:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: "login docker hub"
        run: |
          podman login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}} docker.io
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}}
      - run: |
          sudo apt-get update
          sudo apt-get -y install qemu-user-static buildah less git make podman clamav clamav-freshclam
        name: 'install dev deps'
      - run: buildah unshare make branch_or_ref=master release_tag=master build_ref_images
        name: 'build master images'
      - run: buildah unshare make dist_name=localhost/curl release_tag=master test
        name: 'test image'
      - run: make image_name=localhost/curl:master scan
        name: 'security scan image'
      - run: |
          buildah push curl-dev:master "docker://ghcr.io/curl/curl-container/curl-dev:master"
          buildah push curl-base:master "docker://ghcr.io/curl/curl-container/curl-base:master"
          buildah push curl:master "docker://ghcr.io/curl/curl-container/curl:master"
        name: 'push images to github registry'
