name: build_master_multi_images
on:
  schedule:
    - cron: '30 2 * * * '
  push:
    branches:
    - main
  workflow_dispatch:
  

jobs:
  build_multi_master:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: "login docker hub"
        run: |
          podman login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}} docker.io
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}}
      - name: 'install dev deps'
        run: |
          sudo apt-get update
          sudo apt-get -y install buildah less git make podman qemu qemu-user-static clamav clamav-freshclam   
      - name: 'build multi image'
        run: buildah unshare make branch_or_ref=master release_tag=latest multibuild
      - name: 'push release to docker hub'
        run: |
          buildah manifest push --format v2s2 --all localhost/curl-multi:latest "docker://docker.io/flomesh/curl:latest"
          buildah manifest push --format v2s2 --all localhost/curl-base-multi:latest "docker://docker.io/flomesh/curl-base:latest"
