name: build_master_multi_images
on:
  # schedule:
  #   - cron: '30 2 * * * '
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  build_multi_master:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: "login docker hub"
        run: |
          podman login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}} docker.io
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}}
      - run: |
          sudo apt-get update
          sudo apt-get -y install qemu-user-static buildah less git make podman clamav clamav-freshclam
        name: 'install dev deps'
      - run: buildah unshare make branch_or_ref=master release_tag=master multibuild
        name: 'build multi image'
      - run: buildah unshare make dist_name=localhost/curl-multi release_tag=master test
        name: 'test image'
      - run: make image_name=localhost/curl-multi:master scan
        name: 'security scan image'
      - run: |
          buildah manifest push --all --format v2s2 localhost/curl-base-multi:master "docker://ghcr.io/curl/curl-container/curl-base-multi:master"
          buildah manifest push --all --format v2s2 localhost/curl-multi:master "docker://ghcr.io/curl/curl-container/curl-multi:master"
        name: 'push multi images to github registry'